### ISSUE TITLE
receiveItem no longer gives back the key like storageOnKeyChange

### ISSUE THREAD

**Issue by mordrax** [billstclair/elm-localstorage#2]
Hi Bill,

We used your elm 18 version of localstorage like this:
```
decodeReceivedValues : ( Alfred.Store.Key, Alfred.Store.Value ) -> Maybe Msg
decodeReceivedValues ( key, value ) =
    case key of
        [ "Key1" ] ->
        [ "Key2" ] ->
        [ "Key3" ] ->
```

However, `recieveItem` is now a subscription with only a value mapper so it's no longer possible to work out which `getItem` initiated the call. We have a bunch of these reading from localStorage so it'll be useful to tweak the receiveItem slightly like so:
```
type alias ReceiveItemPort msg =
    (Value -> msg) -> Sub msg                       -- from
    ((Key, Value) -> msg) -> Sub msg             -- to
```

**Comment by billstclair** [comment]
I'll look at this soon. Not tonight, as I'm crashing, but probably tomorrow.

**Comment by billstclair** [comment]
You must have been using version 3.x.x or earlier. I changed the encoding in version 4.x.x, when I added `listKeys`, and that's what I upgraded to 0.19. Time to grok the example again.

The key AND value are included with a `GetItemOperation`. Please use my suggested signature of `(Value  -> msg)-> Sub msg` (aliased as `LocalStorage.SharedTypes.ReceiveItemPort`), for the subscription port, and use my `LocalStorage.SharedTypes.receiveItem` to decode the value, as I did in `example/PortExample.elm`.

Note that I plan another major version bump after I finish `billstclair/elm-port-funnel`, to enable using LocalStorage with a single pair of ports, shared with other PortFunnel-aware packages.

Closing since this was an intentional change between version 3.x.x and 4.x.x.

**Comment by mordrax** [comment]
We were on v4.0.2

And I was using `ReceiveItemPort` but as I detailed above, it doesn't have the Key so I don't know what `getItem` triggered it.

I've since rewrote what little we needed from localStorage as it was a blocker for us.
No need for haste on this. Thanks for your response.

**Comment by billstclair** [comment]
Weird. Since you've fixed your problem, and since I intend to make a major version bump soon, I'll wait to do anything until you ask.
